### ISSUE TITLE
maybe-uninitialized warning in r_jws_serialize

### ISSUE THREAD

**Issue by nlgranger** [babelouest/rhonabwy#1]
GCC9 raises a warning for an maybe uninitialized variable in r_jws_serialize (src/jws.c:268). The if/else branches are missing a default or adj is missing an initial value.

```
rhonabwy-src/src/jws.c: In function 'r_jws_serialize':
rhonabwy-src/src/jws.c:301:31: error: 'adj' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  301 |           s_out_padding = adj - s.size;
      |                           ~~~~^~~~~~~~
rhonabwy-src/src/jws.c:268:16: note: 'adj' was declared here
  268 |   unsigned int adj;
      |                ^~~
```

On a related topic, I'm not sure adjusting CFLAGS in the cmake scripts is idiomatic anymore, even to add `-Wall -Werror` flags ([for example](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#dont-abuse-usage-requirements) or [this](https://gitlab.kitware.com/cmake/cmake/issues/19085#note_573473)), though I don't have an opinion on that myself tbh.

**Comment by babelouest** [comment]
Hello @nlgranger ,

Thanks for the report, another gcc-9 over-the-top static analyzer I forgot to make. I fixed it in the last commit.

**Comment by babelouest** [comment]
Concerning the other topic, I would agree with you but I find it safer to let these flags in the cmake file, therefore travis ci ou github ci can insult me when I forgot some best practices.

Also, in Debian distribution for example, all the `-W` flags are enabled by default when you build the package, so to avoid patching the upstream source code too often, I prefer being safe and let the compiler be strict.
