### ISSUE TITLE
[Windows] Compilation errors

### ISSUE THREAD

**Issue by sfhacker** [babelouest/rhonabwy#20]
- Windows 10 x64
- GCC 11.2.0
- Master branch

C:/src/rhonabwy/src/jws.c: In function 'r_jws_set_properties':
C:/src/rhonabwy/src/jws.c:2138:3: error: unknown type name 'uint'; did you mean 'int'?
 2138 |   uint ui_value;
      |   ^~~~
      |   int
	  
	  
C:/src/rhonabwy/src/jwe.c:4369:3: error: unknown type name 'uint'; did you mean 'int'?
 4369 |   uint ui_value;
      |   ^~~~
      |   int
	  
	  
C:/src/rhonabwy/src/jwt.c:2083:3: error: unknown type name 'uint'; did you mean 'int'?
 2083 |   uint ui_value;
      |   ^~~~
      |   int

We should try, whenever possible, to write portable code!
We should also test as much as we can (on different platforms/architecture).

Thanks for this project anyway.

**Comment by babelouest** [comment]
> We should try, whenever possible, to write portable code!
> We should also test as much as we can (on different platforms/architecture).

We should consider that we can't magically support all platforms that exist, as we work on linux based systems, and we don't have the time/resource to test the code on all other architectures.
