### ISSUE TITLE
Signature files are missing for the newest release (1.1.12)

### ISSUE THREAD

**Issue by mkauf** [babelouest/rhonabwy#32]
The signature files are missing for the newest release: https://github.com/babelouest/rhonabwy/releases

(the builds for various platforms are also missing)

Same problem for the latest builds of [Orcania](https://github.com/babelouest/orcania) and [Yder](https://github.com/babelouest/yder/).

**Comment by babelouest** [comment]
Hello,

I will upload the source files signatures, but the are build for the platforms necessary?

You can easily build your own with cmake, and it takes me a lot of time to maintain the builds...

**Comment by mkauf** [comment]
> I will upload the source files signatures, but the are build for the platforms necessary?

For me, the builds are not necessary (other users may disagree...). I have used the signature files in the past, and I just wanted to ask whether you plan to sign the releases in the future.

**Comment by babelouest** [comment]
I've uploaded the [source signatures](https://github.com/babelouest/rhonabwy/releases/tag/v1.1.12) then. Thanks for the issue @mkauf .
